//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A type defining a date (referred to as the derived date) as a relative offset from another date (referred to as the anchor date) plus optional date adjustments.
 * 
 * <p>Java class for AdjustedRelativeDateOffset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdjustedRelativeDateOffset">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/reporting}RelativeDateOffset">
 *       &lt;sequence>
 *         &lt;element name="relativeDateAdjustments" type="{http://www.fpml.org/FpML-5/reporting}BusinessDayAdjustments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdjustedRelativeDateOffset", propOrder = {
    "relativeDateAdjustments"
})
public class AdjustedRelativeDateOffset
    extends RelativeDateOffset
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected BusinessDayAdjustments relativeDateAdjustments;

    /**
     * Gets the value of the relativeDateAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessDayAdjustments }
     *     
     */
    public BusinessDayAdjustments getRelativeDateAdjustments() {
        return relativeDateAdjustments;
    }

    /**
     * Sets the value of the relativeDateAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessDayAdjustments }
     *     
     */
    public void setRelativeDateAdjustments(BusinessDayAdjustments value) {
        this.relativeDateAdjustments = value;
    }

}
