//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A type defining how the initial or final stub calculation period amounts is calculated. For example, the rate to be applied to the initial or final stub calculation period may be the linear interpolation of two different tenors for the floating rate index specified in the calculation period amount component, e.g. A two month stub period may used the linear interpolation of a one month and three month floating rate. The different rate tenors would be specified in this component. Note that a maximum of two rate tenors can be specified. If a stub period uses a single index tenor and this is the same as that specified in the calculation period amount component then the initial stub or final stub component, as the case may be, must not be included.
 * 
 * <p>Java class for StubCalculationPeriodAmount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StubCalculationPeriodAmount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="calculationPeriodDatesReference" type="{http://www.fpml.org/FpML-5/reporting}CalculationPeriodDatesReference" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="initialStub" type="{http://www.fpml.org/FpML-5/reporting}StubValue" minOccurs="0"/>
 *             &lt;element name="finalStub" type="{http://www.fpml.org/FpML-5/reporting}StubValue" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StubCalculationPeriodAmount", propOrder = {
    "calculationPeriodDatesReference",
    "initialStub",
    "finalStub"
})
public class StubCalculationPeriodAmount
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected CalculationPeriodDatesReference calculationPeriodDatesReference;
    protected StubValue initialStub;
    protected StubValue finalStub;

    /**
     * Gets the value of the calculationPeriodDatesReference property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationPeriodDatesReference }
     *     
     */
    public CalculationPeriodDatesReference getCalculationPeriodDatesReference() {
        return calculationPeriodDatesReference;
    }

    /**
     * Sets the value of the calculationPeriodDatesReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationPeriodDatesReference }
     *     
     */
    public void setCalculationPeriodDatesReference(CalculationPeriodDatesReference value) {
        this.calculationPeriodDatesReference = value;
    }

    /**
     * Gets the value of the initialStub property.
     * 
     * @return
     *     possible object is
     *     {@link StubValue }
     *     
     */
    public StubValue getInitialStub() {
        return initialStub;
    }

    /**
     * Sets the value of the initialStub property.
     * 
     * @param value
     *     allowed object is
     *     {@link StubValue }
     *     
     */
    public void setInitialStub(StubValue value) {
        this.initialStub = value;
    }

    /**
     * Gets the value of the finalStub property.
     * 
     * @return
     *     possible object is
     *     {@link StubValue }
     *     
     */
    public StubValue getFinalStub() {
        return finalStub;
    }

    /**
     * Sets the value of the finalStub property.
     * 
     * @param value
     *     allowed object is
     *     {@link StubValue }
     *     
     */
    public void setFinalStub(StubValue value) {
        this.finalStub = value;
    }

}
