//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A type defining a tenor Period, e.g. one day, three months, Spot.
 * 
 * <p>Java class for TenorPeriod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TenorPeriod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="periodMultiplier" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *           &lt;element name="period" type="{http://www.fpml.org/FpML-5/reporting}PeriodEnum" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="fxTenorPeriod" type="{http://www.fpml.org/FpML-5/reporting}FxTenorPeriodEnum" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TenorPeriod", propOrder = {
    "periodMultiplier",
    "period",
    "fxTenorPeriod"
})
public class TenorPeriod
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger periodMultiplier;
    protected PeriodEnum period;
    protected FxTenorPeriodEnum fxTenorPeriod;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the periodMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeriodMultiplier() {
        return periodMultiplier;
    }

    /**
     * Sets the value of the periodMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriodMultiplier(BigInteger value) {
        this.periodMultiplier = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodEnum }
     *     
     */
    public PeriodEnum getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodEnum }
     *     
     */
    public void setPeriod(PeriodEnum value) {
        this.period = value;
    }

    /**
     * Gets the value of the fxTenorPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link FxTenorPeriodEnum }
     *     
     */
    public FxTenorPeriodEnum getFxTenorPeriod() {
        return fxTenorPeriod;
    }

    /**
     * Sets the value of the fxTenorPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxTenorPeriodEnum }
     *     
     */
    public void setFxTenorPeriod(FxTenorPeriodEnum value) {
        this.fxTenorPeriod = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
