//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpperBound complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpperBound">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="maximumInclusive" type="{http://www.fpml.org/FpML-5/reporting}PositiveDecimal" minOccurs="0"/>
 *         &lt;element name="maximumExclusive" type="{http://www.fpml.org/FpML-5/reporting}PositiveDecimal" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpperBound", propOrder = {
    "maximumInclusive",
    "maximumExclusive"
})
public class UpperBound
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected BigDecimal maximumInclusive;
    protected BigDecimal maximumExclusive;

    /**
     * Gets the value of the maximumInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumInclusive() {
        return maximumInclusive;
    }

    /**
     * Sets the value of the maximumInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumInclusive(BigDecimal value) {
        this.maximumInclusive = value;
    }

    /**
     * Gets the value of the maximumExclusive property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumExclusive() {
        return maximumExclusive;
    }

    /**
     * Sets the value of the maximumExclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumExclusive(BigDecimal value) {
        this.maximumExclusive = value;
    }

}
