//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A type that defines a position asserted by one of the parties.
 * 
 * <p>Java class for AssertedPosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssertedPosition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/reporting}PositionIdAndVersion.model"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/reporting}PositionWithoutId.model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssertedPosition", propOrder = {
    "positionId",
    "version",
    "reportingRoles",
    "constituent",
    "scheduledDate",
    "valuation"
})
public class AssertedPosition
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PositionId positionId;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger version;
    protected ReportingRoles reportingRoles;
    protected PositionConstituent constituent;
    protected List<ScheduledDate> scheduledDate;
    protected List<AssetValuation> valuation;

    /**
     * Gets the value of the positionId property.
     * 
     * @return
     *     possible object is
     *     {@link PositionId }
     *     
     */
    public PositionId getPositionId() {
        return positionId;
    }

    /**
     * Sets the value of the positionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionId }
     *     
     */
    public void setPositionId(PositionId value) {
        this.positionId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the reportingRoles property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingRoles }
     *     
     */
    public ReportingRoles getReportingRoles() {
        return reportingRoles;
    }

    /**
     * Sets the value of the reportingRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingRoles }
     *     
     */
    public void setReportingRoles(ReportingRoles value) {
        this.reportingRoles = value;
    }

    /**
     * Gets the value of the constituent property.
     * 
     * @return
     *     possible object is
     *     {@link PositionConstituent }
     *     
     */
    public PositionConstituent getConstituent() {
        return constituent;
    }

    /**
     * Sets the value of the constituent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionConstituent }
     *     
     */
    public void setConstituent(PositionConstituent value) {
        this.constituent = value;
    }

    /**
     * Gets the value of the scheduledDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduledDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduledDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduledDate }
     * 
     * 
     */
    public List<ScheduledDate> getScheduledDate() {
        if (scheduledDate == null) {
            scheduledDate = new ArrayList<ScheduledDate>();
        }
        return this.scheduledDate;
    }

    /**
     * Gets the value of the valuation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetValuation }
     * 
     * 
     */
    public List<AssetValuation> getValuation() {
        if (valuation == null) {
            valuation = new ArrayList<AssetValuation>();
        }
        return this.valuation;
    }

}
