//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpectedCollateralDelivery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpectedCollateralDelivery">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="cashType" type="{http://www.fpml.org/FpML-5/reporting}CashType" minOccurs="0"/>
 *         &lt;element name="securityType" type="{http://www.fpml.org/FpML-5/reporting}SecurityType" minOccurs="0"/>
 *         &lt;element name="letterOfCreditType" type="{http://www.fpml.org/FpML-5/reporting}LetterOfCreditType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpectedCollateralDelivery", propOrder = {
    "cashTypeOrSecurityTypeOrLetterOfCreditType"
})
public class ExpectedCollateralDelivery
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "cashType", type = CashType.class),
        @XmlElement(name = "letterOfCreditType", type = LetterOfCreditType.class),
        @XmlElement(name = "securityType", type = SecurityType.class)
    })
    protected List<Object> cashTypeOrSecurityTypeOrLetterOfCreditType;

    /**
     * Gets the value of the cashTypeOrSecurityTypeOrLetterOfCreditType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashTypeOrSecurityTypeOrLetterOfCreditType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashTypeOrSecurityTypeOrLetterOfCreditType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashType }
     * {@link LetterOfCreditType }
     * {@link SecurityType }
     * 
     * 
     */
    public List<Object> getCashTypeOrSecurityTypeOrLetterOfCreditType() {
        if (cashTypeOrSecurityTypeOrLetterOfCreditType == null) {
            cashTypeOrSecurityTypeOrLetterOfCreditType = new ArrayList<Object>();
        }
        return this.cashTypeOrSecurityTypeOrLetterOfCreditType;
    }

}
