//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A collection of related trades or positions and the corresponding aggregate exposures generated by these.
 * 
 * <p>Java class for Position complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Position">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/reporting}PositionIdAndVersion.model"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/reporting}PositionStatusInfo.model"/>
 *         &lt;element name="reportingRoles" type="{http://www.fpml.org/FpML-5/reporting}ReportingRoles" minOccurs="0"/>
 *         &lt;element name="constituent" type="{http://www.fpml.org/FpML-5/reporting}PositionConstituent" minOccurs="0"/>
 *         &lt;element name="scheduledDate" type="{http://www.fpml.org/FpML-5/reporting}ScheduledDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="valuation" type="{http://www.fpml.org/FpML-5/reporting}AssetValuation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Position", propOrder = {
    "positionId",
    "version",
    "status",
    "creationDate",
    "originatingEvent",
    "history",
    "reportingRoles",
    "constituent",
    "scheduledDate",
    "valuation"
})
@XmlSeeAlso({
    ReportedPosition.class,
    DefinePosition.class
})
public class Position implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PositionId positionId;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger version;
    protected PositionStatusEnum status;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;
    protected PositionOriginEnum originatingEvent;
    protected PositionHistory history;
    protected ReportingRoles reportingRoles;
    protected PositionConstituent constituent;
    protected List<ScheduledDate> scheduledDate;
    protected List<AssetValuation> valuation;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the positionId property.
     * 
     * @return
     *     possible object is
     *     {@link PositionId }
     *     
     */
    public PositionId getPositionId() {
        return positionId;
    }

    /**
     * Sets the value of the positionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionId }
     *     
     */
    public void setPositionId(PositionId value) {
        this.positionId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link PositionStatusEnum }
     *     
     */
    public PositionStatusEnum getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionStatusEnum }
     *     
     */
    public void setStatus(PositionStatusEnum value) {
        this.status = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the originatingEvent property.
     * 
     * @return
     *     possible object is
     *     {@link PositionOriginEnum }
     *     
     */
    public PositionOriginEnum getOriginatingEvent() {
        return originatingEvent;
    }

    /**
     * Sets the value of the originatingEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionOriginEnum }
     *     
     */
    public void setOriginatingEvent(PositionOriginEnum value) {
        this.originatingEvent = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link PositionHistory }
     *     
     */
    public PositionHistory getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionHistory }
     *     
     */
    public void setHistory(PositionHistory value) {
        this.history = value;
    }

    /**
     * Gets the value of the reportingRoles property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingRoles }
     *     
     */
    public ReportingRoles getReportingRoles() {
        return reportingRoles;
    }

    /**
     * Sets the value of the reportingRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingRoles }
     *     
     */
    public void setReportingRoles(ReportingRoles value) {
        this.reportingRoles = value;
    }

    /**
     * Gets the value of the constituent property.
     * 
     * @return
     *     possible object is
     *     {@link PositionConstituent }
     *     
     */
    public PositionConstituent getConstituent() {
        return constituent;
    }

    /**
     * Sets the value of the constituent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionConstituent }
     *     
     */
    public void setConstituent(PositionConstituent value) {
        this.constituent = value;
    }

    /**
     * Gets the value of the scheduledDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduledDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduledDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduledDate }
     * 
     * 
     */
    public List<ScheduledDate> getScheduledDate() {
        if (scheduledDate == null) {
            scheduledDate = new ArrayList<ScheduledDate>();
        }
        return this.scheduledDate;
    }

    /**
     * Gets the value of the valuation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetValuation }
     * 
     * 
     */
    public List<AssetValuation> getValuation() {
        if (valuation == null) {
            valuation = new ArrayList<AssetValuation>();
        }
        return this.valuation;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
