//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A definition of the mathematical derivative with respect to a specific pricing parameter.
 * 
 * <p>Java class for PricingParameterDerivative complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingParameterDerivative">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="parameterReference" type="{http://www.fpml.org/FpML-5/reporting}AssetOrTermPointOrPricingStructureReference" minOccurs="0"/>
 *           &lt;element name="inputDateReference" type="{http://www.fpml.org/FpML-5/reporting}ValuationReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="calculationProcedure" type="{http://www.fpml.org/FpML-5/reporting}DerivativeCalculationProcedure" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingParameterDerivative", propOrder = {
    "description",
    "parameterReference",
    "inputDateReference",
    "calculationProcedure"
})
public class PricingParameterDerivative
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String description;
    protected AssetOrTermPointOrPricingStructureReference parameterReference;
    protected List<ValuationReference> inputDateReference;
    protected DerivativeCalculationProcedure calculationProcedure;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the parameterReference property.
     * 
     * @return
     *     possible object is
     *     {@link AssetOrTermPointOrPricingStructureReference }
     *     
     */
    public AssetOrTermPointOrPricingStructureReference getParameterReference() {
        return parameterReference;
    }

    /**
     * Sets the value of the parameterReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetOrTermPointOrPricingStructureReference }
     *     
     */
    public void setParameterReference(AssetOrTermPointOrPricingStructureReference value) {
        this.parameterReference = value;
    }

    /**
     * Gets the value of the inputDateReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputDateReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputDateReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValuationReference }
     * 
     * 
     */
    public List<ValuationReference> getInputDateReference() {
        if (inputDateReference == null) {
            inputDateReference = new ArrayList<ValuationReference>();
        }
        return this.inputDateReference;
    }

    /**
     * Gets the value of the calculationProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link DerivativeCalculationProcedure }
     *     
     */
    public DerivativeCalculationProcedure getCalculationProcedure() {
        return calculationProcedure;
    }

    /**
     * Sets the value of the calculationProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivativeCalculationProcedure }
     *     
     */
    public void setCalculationProcedure(DerivativeCalculationProcedure value) {
        this.calculationProcedure = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
