//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:05 AM CDT 
//


package org.fpml.confirmation;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoanParticipation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanParticipation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}PCDeliverableObligationCharac">
 *       &lt;sequence>
 *         &lt;element name="qualifyingParticipationSeller" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanParticipation", propOrder = {
    "qualifyingParticipationSeller"
})
public class LoanParticipation
    extends PCDeliverableObligationCharac
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String qualifyingParticipationSeller;

    /**
     * Gets the value of the qualifyingParticipationSeller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifyingParticipationSeller() {
        return qualifyingParticipationSeller;
    }

    /**
     * Sets the value of the qualifyingParticipationSeller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifyingParticipationSeller(String value) {
        this.qualifyingParticipationSeller = value;
    }

}
