//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:05 AM CDT 
//


package org.fpml.confirmation;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A type defining the parameters required for each of the ISDA defined yield curve methods for cash settlement.
 * 
 * <p>Java class for YieldCurveMethod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="YieldCurveMethod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="settlementRateSource" type="{http://www.fpml.org/FpML-5/confirmation}SettlementRateSource" minOccurs="0"/>
 *           &lt;element name="quotationRateType" type="{http://www.fpml.org/FpML-5/confirmation}QuotationRateTypeEnum"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "YieldCurveMethod", propOrder = {
    "settlementRateSource",
    "quotationRateType"
})
public class YieldCurveMethod
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected SettlementRateSource settlementRateSource;
    @XmlElement(required = true)
    protected QuotationRateTypeEnum quotationRateType;

    /**
     * Gets the value of the settlementRateSource property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementRateSource }
     *     
     */
    public SettlementRateSource getSettlementRateSource() {
        return settlementRateSource;
    }

    /**
     * Sets the value of the settlementRateSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementRateSource }
     *     
     */
    public void setSettlementRateSource(SettlementRateSource value) {
        this.settlementRateSource = value;
    }

    /**
     * Gets the value of the quotationRateType property.
     * 
     * @return
     *     possible object is
     *     {@link QuotationRateTypeEnum }
     *     
     */
    public QuotationRateTypeEnum getQuotationRateType() {
        return quotationRateType;
    }

    /**
     * Sets the value of the quotationRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuotationRateTypeEnum }
     *     
     */
    public void setQuotationRateType(QuotationRateTypeEnum value) {
        this.quotationRateType = value;
    }

}
