//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:05 AM CDT 
//


package org.fpml.confirmation;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The physical delivery conditions for an oil product.
 * 
 * <p>Java class for OilDelivery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OilDelivery">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="pipeline" type="{http://www.fpml.org/FpML-5/confirmation}OilPipelineDelivery"/>
 *           &lt;element name="transfer" type="{http://www.fpml.org/FpML-5/confirmation}OilTransferDelivery"/>
 *         &lt;/choice>
 *         &lt;element name="importerOfRecord" type="{http://www.fpml.org/FpML-5/confirmation}PartyReference" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="absoluteTolerance" type="{http://www.fpml.org/FpML-5/confirmation}AbsoluteTolerance"/>
 *           &lt;element name="percentageTolerance" type="{http://www.fpml.org/FpML-5/confirmation}PercentageTolerance"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OilDelivery", propOrder = {
    "pipeline",
    "transfer",
    "importerOfRecord",
    "absoluteTolerance",
    "percentageTolerance"
})
public class OilDelivery
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected OilPipelineDelivery pipeline;
    protected OilTransferDelivery transfer;
    protected PartyReference importerOfRecord;
    protected AbsoluteTolerance absoluteTolerance;
    protected PercentageTolerance percentageTolerance;

    /**
     * Gets the value of the pipeline property.
     * 
     * @return
     *     possible object is
     *     {@link OilPipelineDelivery }
     *     
     */
    public OilPipelineDelivery getPipeline() {
        return pipeline;
    }

    /**
     * Sets the value of the pipeline property.
     * 
     * @param value
     *     allowed object is
     *     {@link OilPipelineDelivery }
     *     
     */
    public void setPipeline(OilPipelineDelivery value) {
        this.pipeline = value;
    }

    /**
     * Gets the value of the transfer property.
     * 
     * @return
     *     possible object is
     *     {@link OilTransferDelivery }
     *     
     */
    public OilTransferDelivery getTransfer() {
        return transfer;
    }

    /**
     * Sets the value of the transfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link OilTransferDelivery }
     *     
     */
    public void setTransfer(OilTransferDelivery value) {
        this.transfer = value;
    }

    /**
     * Gets the value of the importerOfRecord property.
     * 
     * @return
     *     possible object is
     *     {@link PartyReference }
     *     
     */
    public PartyReference getImporterOfRecord() {
        return importerOfRecord;
    }

    /**
     * Sets the value of the importerOfRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyReference }
     *     
     */
    public void setImporterOfRecord(PartyReference value) {
        this.importerOfRecord = value;
    }

    /**
     * Gets the value of the absoluteTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link AbsoluteTolerance }
     *     
     */
    public AbsoluteTolerance getAbsoluteTolerance() {
        return absoluteTolerance;
    }

    /**
     * Sets the value of the absoluteTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbsoluteTolerance }
     *     
     */
    public void setAbsoluteTolerance(AbsoluteTolerance value) {
        this.absoluteTolerance = value;
    }

    /**
     * Gets the value of the percentageTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link PercentageTolerance }
     *     
     */
    public PercentageTolerance getPercentageTolerance() {
        return percentageTolerance;
    }

    /**
     * Sets the value of the percentageTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentageTolerance }
     *     
     */
    public void setPercentageTolerance(PercentageTolerance value) {
        this.percentageTolerance = value;
    }

}
