//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CashflowCalculationElements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CashflowCalculationElements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numberOfUnits" type="{http://www.fpml.org/FpML-5/reporting}UnderlyerReferenceUnits" minOccurs="0"/>
 *         &lt;element name="notional" type="{http://www.fpml.org/FpML-5/reporting}CashflowNotional" minOccurs="0"/>
 *         &lt;element name="underlyer" type="{http://www.fpml.org/FpML-5/reporting}TradeUnderlyer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="calculatedRate" type="{http://www.fpml.org/FpML-5/reporting}CashflowFixing" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="calculationPeriod" type="{http://www.fpml.org/FpML-5/reporting}CashflowCalculationPeriod" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CashflowCalculationElements", propOrder = {
    "numberOfUnits",
    "notional",
    "underlyer",
    "calculatedRate",
    "calculationPeriod"
})
public class CashflowCalculationElements
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected UnderlyerReferenceUnits numberOfUnits;
    protected CashflowNotional notional;
    protected List<TradeUnderlyer> underlyer;
    protected List<CashflowFixing> calculatedRate;
    protected List<CashflowCalculationPeriod> calculationPeriod;

    /**
     * Gets the value of the numberOfUnits property.
     * 
     * @return
     *     possible object is
     *     {@link UnderlyerReferenceUnits }
     *     
     */
    public UnderlyerReferenceUnits getNumberOfUnits() {
        return numberOfUnits;
    }

    /**
     * Sets the value of the numberOfUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderlyerReferenceUnits }
     *     
     */
    public void setNumberOfUnits(UnderlyerReferenceUnits value) {
        this.numberOfUnits = value;
    }

    /**
     * Gets the value of the notional property.
     * 
     * @return
     *     possible object is
     *     {@link CashflowNotional }
     *     
     */
    public CashflowNotional getNotional() {
        return notional;
    }

    /**
     * Sets the value of the notional property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashflowNotional }
     *     
     */
    public void setNotional(CashflowNotional value) {
        this.notional = value;
    }

    /**
     * Gets the value of the underlyer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the underlyer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnderlyer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TradeUnderlyer }
     * 
     * 
     */
    public List<TradeUnderlyer> getUnderlyer() {
        if (underlyer == null) {
            underlyer = new ArrayList<TradeUnderlyer>();
        }
        return this.underlyer;
    }

    /**
     * Gets the value of the calculatedRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calculatedRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalculatedRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashflowFixing }
     * 
     * 
     */
    public List<CashflowFixing> getCalculatedRate() {
        if (calculatedRate == null) {
            calculatedRate = new ArrayList<CashflowFixing>();
        }
        return this.calculatedRate;
    }

    /**
     * Gets the value of the calculationPeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calculationPeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalculationPeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashflowCalculationPeriod }
     * 
     * 
     */
    public List<CashflowCalculationPeriod> getCalculationPeriod() {
        if (calculationPeriod == null) {
            calculationPeriod = new ArrayList<CashflowCalculationPeriod>();
        }
        return this.calculationPeriod;
    }

}
