//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpectedCollateralDeliveryReturn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpectedCollateralDeliveryReturn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deliver" type="{http://www.fpml.org/FpML-5/reporting}ExpectedCollateralDelivery" minOccurs="0"/>
 *         &lt;element name="return" type="{http://www.fpml.org/FpML-5/reporting}ProposedCollateralDeliveryReturn" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpectedCollateralDeliveryReturn", propOrder = {
    "deliver",
    "_return"
})
public class ExpectedCollateralDeliveryReturn
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected ExpectedCollateralDelivery deliver;
    @XmlElement(name = "return")
    protected List<ProposedCollateralDeliveryReturn> _return;

    /**
     * Gets the value of the deliver property.
     * 
     * @return
     *     possible object is
     *     {@link ExpectedCollateralDelivery }
     *     
     */
    public ExpectedCollateralDelivery getDeliver() {
        return deliver;
    }

    /**
     * Sets the value of the deliver property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpectedCollateralDelivery }
     *     
     */
    public void setDeliver(ExpectedCollateralDelivery value) {
        this.deliver = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the return property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProposedCollateralDeliveryReturn }
     * 
     * 
     */
    public List<ProposedCollateralDeliveryReturn> getReturn() {
        if (_return == null) {
            _return = new ArrayList<ProposedCollateralDeliveryReturn>();
        }
        return this._return;
    }

}
