//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Expected Collateral allows for the definition of collateral that the party making the margin call would prefer to receive or have returned. This can be defined for the Variation Requirement and /or the Segregated Independent Amount Requirement. For deliveries only the type of cash i.e. USD or security type i.e. US Treasuries is expected to be defined. For the return the calling party will know what they posted and therefore can define the expected collateral down to the specific instrument identifier, currency and amount.
 * 
 * <p>Java class for ExpectedCollateral complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpectedCollateral">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="variationMargin" type="{http://www.fpml.org/FpML-5/reporting}ExpectedCollateralDeliveryReturn"/>
 *           &lt;element name="segregatedIndependentAmount" type="{http://www.fpml.org/FpML-5/reporting}ExpectedCollateralDeliveryReturn" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="segregatedIndependentAmount" type="{http://www.fpml.org/FpML-5/reporting}ExpectedCollateralDeliveryReturn"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpectedCollateral", propOrder = {
    "content"
})
public class ExpectedCollateral
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRefs({
        @XmlElementRef(name = "variationMargin", namespace = "http://www.fpml.org/FpML-5/reporting", type = JAXBElement.class),
        @XmlElementRef(name = "segregatedIndependentAmount", namespace = "http://www.fpml.org/FpML-5/reporting", type = JAXBElement.class)
    })
    protected List<JAXBElement<ExpectedCollateralDeliveryReturn>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "SegregatedIndependentAmount" is used by two different parts of a schema. See: 
     * line 718 of file:/C:/eclipse/workspace/fpml/src/main/schema/reporting/fpml-collateral-processes-5-1.xsd
     * line 716 of file:/C:/eclipse/workspace/fpml/src/main/schema/reporting/fpml-collateral-processes-5-1.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ExpectedCollateralDeliveryReturn }{@code >}
     * {@link JAXBElement }{@code <}{@link ExpectedCollateralDeliveryReturn }{@code >}
     * 
     * 
     */
    public List<JAXBElement<ExpectedCollateralDeliveryReturn>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<ExpectedCollateralDeliveryReturn>>();
        }
        return this.content;
    }

}
