//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A type that allows a position to be defined. It includes identification information (ID and version), trade information, etc.
 * 
 * <p>Java class for DefinePosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefinePosition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/reporting}Position">
 *       &lt;sequence>
 *         &lt;element name="forceMatch" type="{http://www.fpml.org/FpML-5/reporting}PositionReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefinePosition", propOrder = {
    "forceMatch"
})
public class DefinePosition
    extends Position
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PositionReference forceMatch;

    /**
     * Gets the value of the forceMatch property.
     * 
     * @return
     *     possible object is
     *     {@link PositionReference }
     *     
     */
    public PositionReference getForceMatch() {
        return forceMatch;
    }

    /**
     * Sets the value of the forceMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionReference }
     *     
     */
    public void setForceMatch(PositionReference value) {
        this.forceMatch = value;
    }

}
