//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterestStatementDirection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterestStatementDirection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="singleDirection" type="{http://www.fpml.org/FpML-5/reporting}SingleDirectionInterestStatementRequirement" minOccurs="0"/>
 *         &lt;element name="bothDirections" type="{http://www.fpml.org/FpML-5/reporting}BothDirectionsInterestStatementRequirement" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterestStatementDirection", propOrder = {
    "singleDirection",
    "bothDirections"
})
public class InterestStatementDirection implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected SingleDirectionInterestStatementRequirement singleDirection;
    protected BothDirectionsInterestStatementRequirement bothDirections;

    /**
     * Gets the value of the singleDirection property.
     * 
     * @return
     *     possible object is
     *     {@link SingleDirectionInterestStatementRequirement }
     *     
     */
    public SingleDirectionInterestStatementRequirement getSingleDirection() {
        return singleDirection;
    }

    /**
     * Sets the value of the singleDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleDirectionInterestStatementRequirement }
     *     
     */
    public void setSingleDirection(SingleDirectionInterestStatementRequirement value) {
        this.singleDirection = value;
    }

    /**
     * Gets the value of the bothDirections property.
     * 
     * @return
     *     possible object is
     *     {@link BothDirectionsInterestStatementRequirement }
     *     
     */
    public BothDirectionsInterestStatementRequirement getBothDirections() {
        return bothDirections;
    }

    /**
     * Sets the value of the bothDirections property.
     * 
     * @param value
     *     allowed object is
     *     {@link BothDirectionsInterestStatementRequirement }
     *     
     */
    public void setBothDirections(BothDirectionsInterestStatementRequirement value) {
        this.bothDirections = value;
    }

}
