//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SegregatedIndependentAmountMarginTerm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegregatedIndependentAmountMarginTerm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/reporting}TransferDetails.model"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegregatedIndependentAmountMarginTerm", propOrder = {
    "minimumTransferAmount",
    "transferRounding"
})
public class SegregatedIndependentAmountMarginTerm implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected BigDecimal minimumTransferAmount;
    protected TransferRounding transferRounding;

    /**
     * Gets the value of the minimumTransferAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinimumTransferAmount() {
        return minimumTransferAmount;
    }

    /**
     * Sets the value of the minimumTransferAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinimumTransferAmount(BigDecimal value) {
        this.minimumTransferAmount = value;
    }

    /**
     * Gets the value of the transferRounding property.
     * 
     * @return
     *     possible object is
     *     {@link TransferRounding }
     *     
     */
    public TransferRounding getTransferRounding() {
        return transferRounding;
    }

    /**
     * Sets the value of the transferRounding property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferRounding }
     *     
     */
    public void setTransferRounding(TransferRounding value) {
        this.transferRounding = value;
    }

}
