//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:10 AM CDT 
//


package org.fpml.reporting;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A Variance Swap Transaction Supplement.
 * 
 * <p>Java class for VarianceSwapTransactionSupplement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VarianceSwapTransactionSupplement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/reporting}Product">
 *       &lt;sequence>
 *         &lt;element name="varianceLeg" type="{http://www.fpml.org/FpML-5/reporting}VarianceLeg" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.fpml.org/FpML-5/reporting}EquityUnderlyerProvisions.model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VarianceSwapTransactionSupplement", propOrder = {
    "varianceLeg",
    "multipleExchangeIndexAnnexFallback",
    "componentSecurityIndexAnnexFallback",
    "localJurisdiction",
    "relevantJurisdiction"
})
public class VarianceSwapTransactionSupplement
    extends Product
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<VarianceLeg> varianceLeg;
    protected Boolean multipleExchangeIndexAnnexFallback;
    protected Boolean componentSecurityIndexAnnexFallback;
    protected CountryCode localJurisdiction;
    protected CountryCode relevantJurisdiction;

    /**
     * Gets the value of the varianceLeg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varianceLeg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVarianceLeg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VarianceLeg }
     * 
     * 
     */
    public List<VarianceLeg> getVarianceLeg() {
        if (varianceLeg == null) {
            varianceLeg = new ArrayList<VarianceLeg>();
        }
        return this.varianceLeg;
    }

    /**
     * Gets the value of the multipleExchangeIndexAnnexFallback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultipleExchangeIndexAnnexFallback() {
        return multipleExchangeIndexAnnexFallback;
    }

    /**
     * Sets the value of the multipleExchangeIndexAnnexFallback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultipleExchangeIndexAnnexFallback(Boolean value) {
        this.multipleExchangeIndexAnnexFallback = value;
    }

    /**
     * Gets the value of the componentSecurityIndexAnnexFallback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isComponentSecurityIndexAnnexFallback() {
        return componentSecurityIndexAnnexFallback;
    }

    /**
     * Sets the value of the componentSecurityIndexAnnexFallback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setComponentSecurityIndexAnnexFallback(Boolean value) {
        this.componentSecurityIndexAnnexFallback = value;
    }

    /**
     * Gets the value of the localJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCode }
     *     
     */
    public CountryCode getLocalJurisdiction() {
        return localJurisdiction;
    }

    /**
     * Sets the value of the localJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCode }
     *     
     */
    public void setLocalJurisdiction(CountryCode value) {
        this.localJurisdiction = value;
    }

    /**
     * Gets the value of the relevantJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCode }
     *     
     */
    public CountryCode getRelevantJurisdiction() {
        return relevantJurisdiction;
    }

    /**
     * Sets the value of the relevantJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCode }
     *     
     */
    public void setRelevantJurisdiction(CountryCode value) {
        this.relevantJurisdiction = value;
    }

}
