//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:05 AM CDT 
//


package org.fpml.confirmation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DividendCompositionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DividendCompositionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="EquityAmountReceiverElection"/>
 *     &lt;enumeration value="CalculationAgentElection"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DividendCompositionEnum")
@XmlEnum
public enum DividendCompositionEnum {


    /**
     * The Equity Amount Receiver determines the composition of dividends (subject to conditions).
     * 
     */
    @XmlEnumValue("EquityAmountReceiverElection")
    EQUITY_AMOUNT_RECEIVER_ELECTION("EquityAmountReceiverElection"),

    /**
     * The Calculation Agent determines the composition of dividends (subject to conditions).
     * 
     */
    @XmlEnumValue("CalculationAgentElection")
    CALCULATION_AGENT_ELECTION("CalculationAgentElection");
    private final String value;

    DividendCompositionEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DividendCompositionEnum fromValue(String v) {
        for (DividendCompositionEnum c: DividendCompositionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
