//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:05 AM CDT 
//


package org.fpml.confirmation;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes the characteristics for american exercise of FX products.
 * 
 * <p>Java class for FxAmericanExercise complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FxAmericanExercise">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/FpML-5/confirmation}FxDigitalAmericanExercise">
 *       &lt;sequence>
 *         &lt;element name="multipleExercise" type="{http://www.fpml.org/FpML-5/confirmation}FxMultipleExercise" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FxAmericanExercise", propOrder = {
    "multipleExercise"
})
public class FxAmericanExercise
    extends FxDigitalAmericanExercise
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected FxMultipleExercise multipleExercise;

    /**
     * Gets the value of the multipleExercise property.
     * 
     * @return
     *     possible object is
     *     {@link FxMultipleExercise }
     *     
     */
    public FxMultipleExercise getMultipleExercise() {
        return multipleExercise;
    }

    /**
     * Sets the value of the multipleExercise property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxMultipleExercise }
     *     
     */
    public void setMultipleExercise(FxMultipleExercise value) {
        this.multipleExercise = value;
    }

}
