//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 08:58:05 AM CDT 
//


package org.fpml.confirmation;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * A description of the legal agreement(s) and definitions that document a party's relationships with other parties
 * 
 * <p>Java class for PartyRelationshipDocumentation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyRelationshipDocumentation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="masterAgreement" type="{http://www.fpml.org/FpML-5/confirmation}MasterAgreement"/>
 *           &lt;element name="creditSupportAgreement" type="{http://www.fpml.org/FpML-5/confirmation}CreditSupportAgreement"/>
 *           &lt;element name="agreement" type="{http://www.fpml.org/FpML-5/confirmation}GenericAgreement"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyRelationshipDocumentation", propOrder = {
    "masterAgreementOrCreditSupportAgreementOrAgreement"
})
public class PartyRelationshipDocumentation
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "agreement", type = GenericAgreement.class),
        @XmlElement(name = "masterAgreement", type = MasterAgreement.class),
        @XmlElement(name = "creditSupportAgreement", type = CreditSupportAgreement.class)
    })
    protected List<Object> masterAgreementOrCreditSupportAgreementOrAgreement;

    /**
     * Gets the value of the masterAgreementOrCreditSupportAgreementOrAgreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the masterAgreementOrCreditSupportAgreementOrAgreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMasterAgreementOrCreditSupportAgreementOrAgreement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericAgreement }
     * {@link MasterAgreement }
     * {@link CreditSupportAgreement }
     * 
     * 
     */
    public List<Object> getMasterAgreementOrCreditSupportAgreementOrAgreement() {
        if (masterAgreementOrCreditSupportAgreementOrAgreement == null) {
            masterAgreementOrCreditSupportAgreementOrAgreement = new ArrayList<Object>();
        }
        return this.masterAgreementOrCreditSupportAgreementOrAgreement;
    }

}
